language: python
before_install:
  - sudo apt-get install -y r-base
  - echo 'local({r = getOption("repos"); r["CRAN"] = "https://cloud.r-project.org/"; options(repos = r)})' > .Rprofile
  - mkdir ~/Rpackage && Rscript -e 'install.packages("rmarkdown", lib="~/Rpackage")'
install:
  - pip install mkdocs==0.17.2
  - pip install mkdocs-material==2.5.2
  - pip install pymdown-extensions
  - pip install python-markdown-math
script:
  - mkdocs build
  - cd rmds && Rscript -e "library(rmarkdown); rmarkdown::render_site()" && mv _site/ ../site/rmds
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  on:
    branch: master
