language: python
install:
  - pip install mkdocs==0.17.2
  - pip install mkdocs-material
  - pip install pymdown-extensions
  - pip install python-markdown-math
script:
  - mkdocs build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  on:
    branch: master
