language: python
before_install:
  - sudo add-apt-repository "deb http://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -sc)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo apt-get update
  - sudo apt-get install r-base
  - echo 'local({r = getOption("repos"); r["CRAN"] = "http://cloud.r-project.org/"; options(repos = r)})' > .Rprofile
  - mkdir ~/Rpackage && Rscript -e 'install.packages(c("digest", "stringr", "knitr", "yaml", "htmltools", "rmarkdown"), lib="~/Rpackage")'
install:
  - pip install mkdocs==0.17.2
  - pip install mkdocs-material==2.5.2
  - pip install pymdown-extensions
  - pip install python-markdown-math
script:
  - mkdocs build
  - cd rmds && Rscript -e "rmarkdown::render_site()" && mv _site/ ../site/rmds
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  on:
    branch: master
