pages:
  - 主页: 'index.md'
  - 目录:
    - 序言:
      - 第二版序言: 'Preface/2016-07-20-Preface-to-the-Second-Edition.md'
      - 第一版序言: 'Preface/2016-07-21-Preface-to-the-First-Edition.md'
    - 1 简介:
      - 1.1 导言: '01 Introduction/2016-07-26-Chapter-1-Introduction.md'
    - 2 监督学习概要:
      - 2.1 导言: '02 Overview of Supervised Learning/2.1 Introduction.md'
      - 2.2 变量类型和术语: '02 Overview of Supervised Learning/2.2 Variable Types and Terminology.md'
      - 2.3 两种预测的简单方法: '02 Overview of Supervised Learning/2.3 Two Simple Approaches to Prediction.md'
      - 2.4 统计判别理论: '02 Overview of Supervised Learning/2.4 Statistical Decision Theory.md'
      - 2.5 高纬问题的局部方法: '02 Overview of Supervised Learning/2.5 Local Methods in High Dimensions.md'
      - 2.6 统计模型，监督学习和函数逼近: '02 Overview of Supervised Learning/2.6 Statistical Models, Supervised Learning and Function Approximation.md'
      - 2.7 结构化的回归模型: '02 Overview of Supervised Learning/2.7 Structured Regression Models.md'
      - 2.8 限制性估计的类别: '02 Overview of Supervised Learning/2.8 Classes of Restricted Estimators.md'
      - 2.9 模型选择和偏差-方差的权衡: '02 Overview of Supervised Learning/2.9 Model Selection and the Bias-Variance Tradeoff.md'
      - 文献笔记: '02 Overview of Supervised Learning/Bibliographic Notes.md'
    - 3 回归的线性方法:
      - 3.1 导言: '03 Linear Methods for Regression/3.1 Introduction.md'
      - 3.2 线性回归模型和最小二乘法: '03 Linear Methods for Regression/3.2 Linear Regression Models and Least Squares.md'
      - 3.3 子集的选择: '03 Linear Methods for Regression/3.3 Subset Selection.md'
      #- 收缩的方法: '03 Linear Methods for Regression/3.4 Shrinkage Methods.md'

site_name: 'ESL CN'

site_description: 'The Elements of Statistical Learning(ESL) 的中文翻译'

site_url: https://szcf-weiya.github.io/ESL-CN/

repo_url: https://szcf-weiya.github.io

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML
  - js/mymathjax.js

extra_css:
  - css/newsprint.css
  - css/admonition_fix.css

docs_dir: 'docs'

theme_dir: 'yeti'
