pages:
  - 主页: 'index.md'
  - 目录:
    - 序言:
      - 第二版序言: 'Preface/2016-07-20-Preface-to-the-Second-Edition.md'
      - 第一版序言: 'Preface/2016-07-21-Preface-to-the-First-Edition.md'
    - 1 简介:
      - 1.1 导言: '01 Introduction/2016-07-26-Chapter-1-Introduction.md'
    - 2 监督学习概要:
      - 2.1 导言: '02 Overview of Supervised Learning/2.1 Introduction.md'
      - 2.2 变量类型和术语: '02 Overview of Supervised Learning/2.2 Variable Types and Terminology.md'
      - 2.3 两种预测的简单方法: '02 Overview of Supervised Learning/2.3 Two Simple Approaches to Prediction.md'
      - 2.4 统计判别理论: '02 Overview of Supervised Learning/2.4 Statistical Decision Theory.md'
      - 2.5 高维问题的局部方法: '02 Overview of Supervised Learning/2.5 Local Methods in High Dimensions.md'
      - 2.6 统计模型，监督学习和函数逼近: '02 Overview of Supervised Learning/2.6 Statistical Models, Supervised Learning and Function Approximation.md'
      - 2.7 结构化的回归模型: '02 Overview of Supervised Learning/2.7 Structured Regression Models.md'
      - 2.8 限制性估计的类别: '02 Overview of Supervised Learning/2.8 Classes of Restricted Estimators.md'
      - 2.9 模型选择和偏差-方差的权衡: '02 Overview of Supervised Learning/2.9 Model Selection and the Bias-Variance Tradeoff.md'
      - 文献笔记: '02 Overview of Supervised Learning/Bibliographic Notes.md'
    - 3 回归的线性方法:
      - 3.1 导言: '03 Linear Methods for Regression/3.1 Introduction.md'
      - 3.2 线性回归模型和最小二乘法: '03 Linear Methods for Regression/3.2 Linear Regression Models and Least Squares.md'
      - 3.3 子集的选择: '03 Linear Methods for Regression/3.3 Subset Selection.md'
      - 3.4 收缩的方法: '03 Linear Methods for Regression/3.4 Shrinkage Methods.md'
      - 3.5 运用派生输入方向的方法: '03 Linear Methods for Regression/3.5 Methods Using Derived Input Directions.md'
      - 3.6 选择和收缩方法的比较: '03 Linear Methods for Regression/3.6 A Comparison of the Selection and Shrinkage Methods.md'
      - 3.7 多重输出的收缩和选择: '03 Linear Methods for Regression/3.7 Multiple Outcome Shrinkage and Selection.md'
      #- 3.8 Lasso和相关路径算法的补充: '03 Linear Methods for Regression/3.8 More on the Lasso and Related Path Algorithms.md'
    - 4 分类的线性方法:
      - 4.1 导言: '04 Linear Methods for Classification/4.1 Introduction.md'
      - 4.2 指示矩阵的线性回归: '04 Linear Methods for Classification/4.2 Linear Regression of an Indicator Matrix.md'
      - 4.3 线性判别分析: '04 Linear Methods for Classification/4.3 Linear Discriminant Analysis.md'
      - 4.4 逻辑斯蒂回归: '04 Linear Methods for Classification/4.4 Logistic Regression.md'
      - 4.5 分离超平面: '04 Linear Methods for Classification/4.5 Separating Hyperplanes.md'
    #- 5 基本展开和正规化:
    #- 6 核光滑方法:
    #- 7 模型评估及选择:
    #- 8 模型推断和平均:
    #- 9 增广模型，树，以及相关方法:
    #- 10 加速和增长树:
    #- 11 神经网络:
    - 12 支持向量机和灵活的判别方法:
      - 12.1 导言: '12 Support Vector Machines and Flexible Discriminants/12.1 Introduction.md'
      - 12.2 支持向量分类器: '12 Support Vector Machines and Flexible Discriminants/12.2 The Support Vector Classifier.md' 
    #- 13 原型方法和最近邻:
    #- 14 非监督学习:
    #- 15 随机森林:
    #- 16 整体学习:
    #- 17 无向图模型:
    #- 18 高维问题

site_name: 'ESL CN'

site_description: 'The Elements of Statistical Learning(ESL) 的中文翻译'

site_url: https://szcf-weiya.github.io/ESL-CN/

repo_url: https://szcf-weiya.github.io

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math

extra_javascript:
  - js/MathJax/MathJax.js?config=TeX-AMS_CHTML
  - js/mymathjax.js

extra_css:
  - css/newsprint.css
  - css/admonition_fix.css

docs_dir: 'docs'

theme_dir: 'yeti'
